# Generated by Django 2.2 on 2020-03-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=128, verbose_name='操作系统')),
                ('type', models.CharField(max_length=128, verbose_name='机器类型')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem', models.FloatField(blank=True, null=True, verbose_name='内存')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='处理器')),
                ('disk', models.FloatField(blank=True, null=True, verbose_name='硬盘')),
                ('nic', models.CharField(max_length=128, verbose_name='网络地址')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.System', verbose_name='操作系统')),
            ],
        ),
    ]
